### ISSUE TITLE
add counter for meat bulbs/lure plants

### ISSUE THREAD

**Issue by TheBlues7095** [gyroplast/mod-dont-starve-prefab-counter#4]
Can you add a tally of how many lure plants are in a world? I'd like to know when a new one spawns during spring.

**Comment by gyroplast** [comment]
Adding lure plants/meat bulbs to the count sounds reasonable to me. I just have to watch that I'm not exceeding the available back buffer in the chat, but one more should fit even in worst case when all counts are printed.
Prefab code is "lureplant".
